### ISSUE TITLE
Freeze/crash on Windows 19H1

### ISSUE THREAD

**Issue by 19lmyers** [mcdenis/AccentApplicator#5]
For a while I've had an issue where the app freezes on 19H1. Specifically, trying to select one of the top two checkboxes will freeze the app and prevent me from clicking the OK button. (The boxes also uncheck themselves.)

**Comment by mcdenis** [comment]
Thanks for reporting the issue. I have just clean-installed the app on a machine running Windows build 18305 and have encountered the same symptoms that you are describing. I have conducted a few tests and suspect that the issue is caused by a bug in recent Windows Insider builds. For now, I will just wait and see.

**Comment by mcdenis** [comment]
@19lmyers I have tested the app on build 18343 and it seems to work fine now. Another user has also mentioned that it works as expected on release 19H1. When you have a chance, could you try the app again and report back?

**Comment by 19lmyers** [comment]
Just tried it again, it's working now!

>

**Comment by mcdenis** [comment]
Wonderful, thank you.
